services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
  app:
    image: node:alpine
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - ${LOCAL_PORT}:${PORT}
    working_dir: /app
    command: npm run start
    depends_on:
      - mongo
      - mongo-express
